# Generated by Django 6.0.1 on 2026-09-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, unique=True)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('idade_cliente', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='ingressos.categoria')),
            ],
        ),
    ]
